### PR TITLE
feat: UDP Writer

### PR DESCRIPTION
**Pull request by glushkovds**
## Proposed Changes

Ability to write to DB via UDP protocol

## Checklist

- [ ] CHANGELOG.md updated
- [ ] Rebased/mergeable
- [ ] A test has been added if appropriate
- [ ] `make test` completes successfully
- [ ] Commit messages are in [semantic format](https://seesparkbox.com/foundry/semantic_commit_messages)
- [ ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by sranka** [comment]
@glushkovds Can you please share your motivation of why do you need UDP and why can't you use the v2-supported HTTP?

**Comment by glushkovds** [comment]
Idea is very simple: my application is critical in response time, I can't afford any delays. As you know TCP protocol is synchronous, and app must wait response from Influxdb server. I'd rather settle for lost metrics than risk getting timeouts from the db server.

My PR looks like draft? Maybe. If you approve my beginning, I will put things in order.

**Comment by bednar** [comment]
Hi @glushkovds,

thanks for PR 👍

It sounds reasonable and We will be happy to accept this PR. Could you leave a comment after your PR will be ready to review?

Regards

**Comment by sranka** [comment]
I think that using (and offering) a non-blocking HTTP during write might be a better solution for this InfluxDB client library. The herein provided UDP solution conceptually creates a client to telegraf.

**Comment by glushkovds** [comment]
@sranka what do you mean non-blocking HTTP? Something like ?
```php
exec("wget -O /dev/null $url --background")
```
Guzzle natively does not support real asyncronous mode. `Client::requestAsync()` returns a promise and actually does not perform request.
Anyway non-blocking TCP looks like blocking UDP 😀

**Comment by sranka** [comment]
@glushkovds yes, I mean [Guzzle Async Requests](https://docs.guzzlephp.org/en/stable/quickstart.html#async-requests). Indeed, it would work like UDP (when configured with no retries), and it would work for all users without having to install and configure telegraf, which is the main benefit.

**Comment by glushkovds** [comment]
@sranka Yes, you are right, using UDP requires telegraf with listener plugin, this is the price of true asynchronous mode.
As I wrote earlier Guzzle `getAsync` only creates promise, and does not perform request. Request will be performed in `$promise = wait()` method.

**Comment by sranka** [comment]
Thank you @glushkovds for the explanation. If there is no real async, the existing client write API shall be accompanied with a big warning.

**Pull request closed without merging**
