### PR TITLE
feat: Add support for Guzzle client version 7.x

### LINKED ISSUE #47: Add support for Guzzle client version 7.x.
__Proposal:__
 "guzzlehttp/guzzle": "^6.2|^7"

__Current behavior:__
 "guzzlehttp/guzzle": "^6.2"

__Desired behavior:__
Supporting guzzle ^7.0 will allow this library to be used with Laravel 8.

__Alternatives considered:__
.

__Use case:__
Supporting guzzle ^7.0 will allow this library to be used with Laravel 8.

### PR DESCRIPTION
**Pull request by kanashin**
Closes #47

## Proposed Changes

Add support for Guzzle client version 7.x

## Checklist

- [ ] CHANGELOG.md updated
- [ ] Rebased/mergeable
- [ ] A test has been added if appropriate
- [ ] `make test` completes successfully
- [ ] Commit messages are in [semantic format](https://seesparkbox.com/foundry/semantic_commit_messages)
- [ ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Review by bednar — CHANGES_REQUESTED** [review]
@kanashin thanks for your PR.

Please, could you look at failing test? 

`testRetryConnectionError - InfluxDB2Test.WriteApiBatchingTest`

image

https://app.circleci.com/pipelines/github/influxdata/influxdb-client-php/452/workflows/674d5232-6103-4eb4-8d01-a72c890b0a9d/jobs/1254

**Comment by kanashin** [comment]
Hello!

Sorry but I cannot:

`make test`

```
The command 'docker-compose' could not be found in this WSL 1 distro.
We recommend to convert this distro to WSL 2 and activate
the WSL integration in Docker Desktop settings.

See https://docs.docker.com/docker-for-windows/wsl/ for details.

Makefile:31: recipe for target 'start-server' failed
make: *** [start-server] Error 1
```

**Comment by bednar** [comment]
Instead of `make test` you could use (from root of project):

```console
docker run -d -p "8086:8086" quay.io/influxdb/influxdb:2.0.0-rc
./scripts/influxdb-onboarding.sh
composer run test
```

**Comment by kanashin** [comment]
Closing this PR. I cannot do a query, so maybe the problem is guzzle. Moving to something else.

Thanks, and sorry for wasting your time.

 +"message": "[0] cURL error 3:  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for /api/v2/query?org={$org}"
  +"exception": "InfluxDB2\ApiException"

**Comment by kanashin** [comment]
After a few more tests, I actually was able to do the query by setting the variable INFLUXDB_HTTP_FLUX_ENABLED to 1 in the docker container (mentioned https://github.com/influxdata/influxdb-client-php#influxdb-18-api-compatibility) or by doing a queryRaw, so it seems that Guzzle 7 works as well.

However, I do not understand the new "format" of the data in InfluxDB (array of FluxTable whose we have to map and then flatten and then merge) and our company decided that cannot invest more resources migrating from InfluxDB 1.x in which we had a "simple array of data" that was enough.

One more time, thanks and sorry for wasting your time.

**Comment by bednar** [comment]
If you would like to have a flattened data you should use [pivot() function](https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/pivot/) in your query.

The InfluxDB v2 uses Annotated CSV as a response format - https://docs.influxdata.com/influxdb/v2.0/reference/syntax/annotated-csv/

**Comment by kanashin** [comment]
I do not understand why InfluxDB 2 is so complicated.

After losing 2 days, I still can't do a simple `Select * from measurement` and return a JSON to the client. In addition, enabling the old API with InfluxQL which at least was understandable is very complicated.

Maybe I'm not understanding the roadmap of InfluxDB 2 and I should move to another DB.

**Comment by bednar** [comment]
The `Flux` comes with more features than have the IFQL. 

How we can help you in `php` client? What about new method on the `QueryApi` that will return json list of Flux records?

**Pull request closed without merging**
